// Integration Flags - PRODUCTION ONLY - NO MOCKS
    ENABLE_REAL_CERTIFICATES: true,
    ENABLE_BIOMETRIC_VALIDATION: true,
    ENABLE_GOVERNMENT_INTEGRATION: true,
    USE_MOCK_DATA: false,
    FORCE_REAL_APIS: true,
    BYPASS_MODE: false,